server:
  port: 8088
application:
spring:
#
  datasource:
    username: root
    password: cl1991625
    url: jdbc:mysql://localhost:3306/jwt-security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
  # 指定全局配置文件位置,不用配置也行
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.me.jwtsecurity.pojo


#showSql
logging:
  level:
    com:
      example:
        mapper : debug
