server:
  port: 8088
application:
spring:
#
  datasource:
    username: root
    password: cl1991625
    url: jdbc:mysql://localhost:3306/jwt-security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
# 指定全局配置文件位置,不用配置也行
#  config-location: classpath:mybatis/mybatis-config.xml
#指定mapper.xml配置文件路径,放在resources路径下(不知道位置放到java目录下运行不起来)
  mapper-locations: classpath:mapper/*.xml
#给包起别名,在UserMapping.xml配置文件中可以直接使用:<select id="selectUserById" resultType="com.example.me.jwtsecurity.pojo.User">可简写写成<select id="selectUserById" resultType="user">
  type-aliases-package: com.example.pojo
  # spring.security.user
  security:
    user:
      name: 陈亮
      password: $2a$10$MNuMiZgNMq82GNdBp29ZDulPEL8YfIrjezSQWYgJw8YDuIsfVb78S
#    如果不想一开始就使能Spring Security，可以在配置文件中做如下的配置：
    basic:
      enabled: false
  #监控关闭:
  management:
    security:
      enabled: false
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
